In [2]:
import numpy as np
import time
import random
import math

In [136]:
python_list = []
for i in range(1000):
    row = []
    for j in range(1000):
        angka = random.randint(0, 99)
        row.append(angka)
    python_list.append(row)

numpy_matrix = np.random.randint(0, 100, size=(1000,1000))

start = time.time()
total = 0
for row in python_list:
    for angka in row:
        total += angka
time_list = time.time() - start


start = time.time()
total_numpy = np.sum(numpy_matrix)
time_numpy = time.time() - start

print(f"Python list: {time_list:.6f} detik")
print(f"NumPy matrix: {time_numpy:.6f} detik")

Python list: 0.054103 detik
NumPy matrix: 0.001002 detik


In [141]:
A = np.array([1, 2, 3])  # shape (3,)
B = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  # shape (3, 3)

C = A + B
print(C)

[[11 22 33]
 [41 52 63]
 [71 82 93]]


In [145]:
array = np.zeros((2, 4))
print (array.shape)
print (array.dtype)

(2, 4)
float64


In [ ]:
x = np.array([5, 10, 15])
y = np.array([2, 2, 2])

print("Sum:", x+y)
print("Multiplication:", x*y)
print("Division:", x/y)
#Numpy bisa handle semua

Sum: [ 7 12 17]
Multiplication: [10 20 30]
Division: [2.5 5.  7.5]


In [3]:
A = np.array([100, 200, 300])
B = np.array([[1, 2, 3], [4, 5, 6]])

print(A-B)

#bisa dijalankan
#outputnya:
#[[ 99 198 297]
# [ 96 195 294]]

#numpy bisa handle itu karena memiliki sifat element wise, sehingga otomatis bisa handle yang shapenya tidak sesuai dan perlu repeat

[[ 99 198 297]
 [ 96 195 294]]


In [40]:
A = np.random.randint(0, 100, size=(3, 4))
B = np.random.randint(0, 100, size=(4, 5))

result = np.dot(A, B)
print(result)
print(result.shape)
manual_calc = np.dot(A[0, :], B[:, 0])
print(f"result[0, 0] dari np.dot: {result[0, 0]}")
print(f"result[0, 0] manual calc: {manual_calc}")
print(f"Match? {result[0, 0] == manual_calc}")



[[ 3994  6394 10374  8998  7598]
 [ 3339  3619  2519  2333  4753]
 [11436  8441 14673 12989 15893]]
(3, 5)
result[0, 0] dari np.dot: 3994
result[0, 0] manual calc: 3994
Match? True


In [42]:
user_pref = [0.8, 0.3, 0.9, 0.2]
movie_feat = [0.7, 0.2, 0.8, 0.3]

result = np.dot(user_pref, movie_feat)
print(result)

#movie ini cocok dengan user preference, karena memiliki nilai yang tinggi pada fitur yang sama dengan preferensi user.


1.4


In [52]:
A = [[1, 2], [3, 4], [5, 6]]
B = [[7, 8, 9], [10, 11, 12]]


result = np.dot(A, B)
print(result)
print(result.shape)
print(result[2, 1])

manual = A[2][0] * B[0][1] + A[2][1] * B[1][1]
print(manual)

#match

[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]
(3, 3)
106
106


In [57]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[-1])
print(arr[-2])
print(arr[-5])

50
40
10


In [58]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print(matrix[0])        # baris 0 (seluruh kolom)
print(matrix[0, 2])     # baris 0, kolom 2
print(matrix[1, :])     # baris 1, semua kolom
print(matrix[:, 2])     # semua baris, kolom 2
print(matrix[0:2, 1:3]) # baris 0-1, kolom 1-2

[1 2 3 4]
3
[5 6 7 8]
[ 3  7 11]
[[2 3]
 [6 7]]


In [61]:
arr = np.array([1, 5, 3, 8, 2, 9])
condition = arr > 4
print(condition)
print(arr[condition])

[False  True False  True False  True]
[5 8 9]


In [165]:
array = np.random.randint(0, 21, size=(5,5))
satu = array[2:4, 1:3]
condition = satu > 5
print(array)

print(satu)
print(condition)
print(satu[condition])

[[13 16 17 14 11]
 [19  6  9 20  2]
 [10  1  7  7 14]
 [ 8  3 12 16  9]
 [10  6 19  4 15]]
[[ 1  7]
 [ 3 12]]
[[False  True]
 [False  True]]
[ 7 12]


In [315]:
array = np.random.randint(0,21, size=(5,5))
condition = array > 10
print(len(array[condition]))
print((len(array[condition])/25*100), "%")

11
44.0 %
