In [75]:
import numpy as np
import random
import time

In [42]:
array = np.array([5,10,15,20,25])
zeroarray = np.zeros((3,3))
arraygenap = np.arange(0,20,2)
arrayrandom = np.random.randint(0, 51, size = (4,4))

print(array)
print(zeroarray)
print(arraygenap)
print(arrayrandom)

print("Shape array : ", arrayrandom.shape)
print("Dtype array : ", arrayrandom.dtype)
print("Elemen terbesar : ", np.max(arrayrandom))
print("Elemen terkecil : ", np.min(arrayrandom))

[ 5 10 15 20 25]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[ 0  2  4  6  8 10 12 14 16 18]
[[50  7 43 38]
 [45 22 28 30]
 [25 32  3 38]
 [17 16 14 28]]
Shape array :  (4, 4)
Dtype array :  int32
Elemen terbesar :  50
Elemen terkecil :  3


In [84]:
python_list = []
for i in range(500):
    row = []
    for j in range(1000):
        angka = random.randint(0, 99)
        row.append(angka)
    python_list.append(row)

numpy_matrix = np.random.randint(0, 100, size=(500,1000))

start = time.time()
total = 0
for row in python_list:
    for angka in row:
        total += angka
time_list = time.time() - start


start = time.time()
total_numpy = np.sum(numpy_matrix)
time_numpy = time.time() - start

print(f"Python list: {time_list:.9f} detik")
print(f"NumPy matrix: {time_numpy:.9f} detik")

Python list: 0.026684284 detik
NumPy matrix: 0.001000166 detik
