In [1]:
import numpy as np

In [6]:
data = np.array([60, 70, 80, 90, 100])
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))

Mean: 80.0
Median: 80.0
Standard Deviation: 14.142135623730951


In [20]:
matrix = np.array([
    [60, 70, 80],
    [90, 100, 110],
    [40, 50, 60]
])

print(np.mean(matrix))
print(np.mean(matrix, axis=0))
print(np.mean(matrix, axis=1))

73.33333333333333
[63.33333333 73.33333333 83.33333333]
[ 70. 100.  50.]


In [127]:
array = np.random.randint(1, 11, size= (4,5))
print(array)
print("Mean: ", np.mean(array, axis=1))
print("STD:", np.std(array, axis=0))
print("Index Nilai Maksimum: ", np.argmax(array, axis=1))

#cek manual

newarray = array[0, 0:]
print(newarray)
max = -1
valuemax = -1
j = -1
for i in newarray:
    j+=1
    if i > valuemax:
        valuemax = i
        max = j

print("Apakah match?", max == np.argmax(array, axis=1)[0])

[[ 5  4  2  4  2]
 [ 3  2  5  6  6]
 [ 6  6  3 10  8]
 [ 2  3  5  8  6]]
Mean:  [3.4 4.4 6.6 4.8]
STD: [1.58113883 1.47901995 1.29903811 2.23606798 2.17944947]
Index Nilai Maksimum:  [0 3 3 3]
[5 4 2 4 2]
Apakah match? True
