In [2]:
import numpy as np

In [78]:
def normalize(matrix):
    mean = np.mean(matrix)
    std = np.std(matrix)
    normalized = (matrix - mean) / std
    return normalized

array = np.random.randint(1, 25, size=(4,4))

print(array)
print("mean sebelum normalized: ", np.mean(array))
print("std sebelum normalized: ", np.std(array))
print(normalize(array))
print("mean habis normalized:", np.mean(normalize(array)))
print("std habis normalized:", np.std(normalize(array)))

[[ 3  5 14  1]
 [ 7 17 22  1]
 [22  2 24  5]
 [15  8 22 22]]
mean sebelum normalized:  11.875
std sebelum normalized:  8.454843286542927
[[-1.0496942  -0.8131434   0.25133523 -1.28624501]
 [-0.57659259  0.60616144  1.19753846 -1.28624501]
 [ 1.19753846 -1.16796961  1.43408927 -0.8131434 ]
 [ 0.36961064 -0.45831719  1.19753846  1.19753846]]
mean habis normalized: 2.7755575615628914e-17
std habis normalized: 1.0
